spring.application.name=jobportal

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jobportal}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}

# Server
server.port=${PORT:8080}